### ISSUE TITLE
Checklist of to-dos!

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter-exporter-sinatra#2]
* [x] complete https://github.com/publiclab/mapknitter-exporter/pull/4
* [x] connect with the new Gem https://github.com/publiclab/mapknitter-exporter
* [ ] produce `status.json` with new Export class
* [ ] ...
* [ ] testing!

**Comment by jywarren** [comment]
Moving to just use remaining issues instead of this list, since we've gotten a lot done and broken out the rest into issues!
